### ISSUE TITLE
Progress Indicator Interface

### ISSUE THREAD

**Issue by NoamDev** [tonlabs/DeBot-IS-consortium#36]
I think a progress indicator would be very useful on debots.
Instead of some mundane "working..." message, you'd be able to show circular progress indicator, or an ascii equivalent on cli.
the intefrace may also contain progress bar:)

What do you think?

**Comment by NoamDev** [comment]
I'm thinking something like:
showCircularProgressIndicator(optional string text);

**Comment by Keshoid** [comment]
Please, create a proposal for this interface. We will discuss it.
